name: Deploy to VPS E

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - closed

jobs:
  checkout-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  setup-node:
    runs-on: ubuntu-latest
    needs: checkout-code
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

  install-dependencies:
    runs-on: ubuntu-latest
    needs: setup-node
    steps:
      - name: Install dependencies
        run: npm install

  build-app:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Build the app
        run: npm run build

  copy-to-vps:
    runs-on: ubuntu-latest
    needs: build-app
    steps:
      - name: Copy artifacts to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "production/*"
          target: "/var/www/html/nutrigenic-frontend"
