name: Deploy to VPS

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      TERM: xterm

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install

      - name: Build the app
        run: |
          npm run build

      - name: SSH Agent Setup
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSHKEY }}

      - name: Remove existing files inside target directory on VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} -p ${{ secrets.PORT }} 'rm -rf /var/www/html/nutrigenic-frontend/*'

      - name: Copy artifacts to VPS
        run: |
          scp -o StrictHostKeyChecking=no -P ${{ secrets.PORT }} -i ~/.ssh/id_rsa -r production/* ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/var/www/html/nutrigenic-frontend
